services:
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public_html:/var/www/public_html
    depends_on:
      - application
    restart: always

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: "npm start"
