services:
  # Next.js Application
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calora-nextjs
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - calora-network

  # nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: calora-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextjs-app
    networks:
      - calora-network

networks:
  calora-network:
    driver: bridge